#!/usr/bin/env python3
"""Generate the stock drum-machine rhythm data as C, from the user's own stock .mr.

The stock FB200 firmware (V1.0.1) keeps its drum sequencer data in block 0:

  * 90 event lists (4712 u32 words) that the vendor loader memcpy's from block 0
    payload offset 0x1e39c to DTCM 0x20000000 (load-table entry 1, not compressed);
  * the event-list lengths (90 u32) in the ITCM image at 0x1c8ac;
  * the 40 user rhythms -> event-list map and the beats-per-bar table, inside
    the LZ-compressed DTCM data (load-table entry 2: block 0 offset 0x22d3c,
    0x141a4 bytes -> DTCM 0x200049a0). They are float/u32 tables at DTCM
    0x20007fd8 (units), 0x20007f38 (tens) and 0x20008078 (beats per bar).

Event word: bits 31..16 = ticks from the previous event (120 ticks per beat),
bits 15..8 = sample index + 1 (0 = rest, 0xff = end of list, loop), bits 7..0 =
velocity (gain = velocity / 127).

This is vendor data: the output goes to the (gitignored) build directory and
is never committed. Usage:

    gen_stock_drums.py fb200-stock.mr build/stock_drums_data.c
"""

from __future__ import annotations

import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from fb200.firmware import MrFile

N_PATTERNS = 90
N_RHYTHMS = 40
EVENTS_OFF, EVENTS_LEN = 0x1E39C, 0x49A0          # block 0 payload, raw copy
LZ_OFF, LZ_LEN, LZ_DST = 0x22D3C, 0x141A4, 0x200049A0
ITCM_PAYLOAD_OFF, ITCM_BASE = 0x7D4, 0x400        # ITCM image = payload[0x7d4:] at 0x400
LENS_ITCM = 0x1C8AC
UNITS, TENS, BEATS = 0x20007FD8, 0x20007F38, 0x20008078


def arm_lz_decompress(src: bytes, pos: int, length: int) -> bytes:
    """Arm Compiler scatter-load LZ77 (the stock loader's routine at block 0 +0x43c)."""
    out = bytearray()
    tok = src[pos]
    pos += 1
    while True:
        lit = tok & 3
        if lit == 0:
            lit = src[pos]
            pos += 1
        mlen = tok >> 4
        if mlen == 0:
            mlen = src[pos]
            pos += 1
        n = lit - 1
        out += src[pos:pos + n]
        pos += n
        if mlen:
            off = src[pos]
            pos += 1
            if tok & 0xC == 0xC:
                off += src[pos] << 8
                pos += 1
            else:
                off += (tok & 0xC) << 6
            p = len(out) - off
            for _ in range(mlen + 2):
                out.append(out[p])
                p += 1
        if len(out) >= length:
            return bytes(out[:length])
        tok = src[pos]
        pos += 1


def extract(mr_path: Path) -> dict:
    blk = MrFile.from_path(mr_path).blocks[0].data
    events = list(struct.unpack_from(f"<{EVENTS_LEN // 4}I", blk, EVENTS_OFF))
    lens = list(struct.unpack_from(f"<{N_PATTERNS}I", blk,
                                   ITCM_PAYLOAD_OFF + LENS_ITCM - ITCM_BASE))
    dt = arm_lz_decompress(blk, LZ_OFF, LZ_LEN)

    def rd(addr: int, fmt: str, n: int):
        return struct.unpack_from(f"<{n}{fmt}", dt, addr - LZ_DST)

    units, tens = rd(UNITS, "f", N_RHYTHMS), rd(TENS, "f", N_RHYTHMS)
    rhythm = [int(u + 10 * t) for u, t in zip(units, tens)]
    beats = list(rd(BEATS, "I", N_PATTERNS))
    # sanity: the lists tile the event table exactly and every list ends in 0xff
    if sum(lens) != len(events):
        raise SystemExit(f"length table ({sum(lens)}) != event words ({len(events)}): not V1.0.1?")
    off = 0
    for i, n in enumerate(lens):
        if (events[off + n - 1] >> 8) & 0xFF != 0xFF:
            raise SystemExit(f"pattern {i} does not end with an end marker")
        off += n
    if not all(0 <= p < N_PATTERNS for p in rhythm) or not all(1 <= b <= 9 for b in beats):
        raise SystemExit("rhythm map / beats table out of range: not V1.0.1?")
    return {"events": events, "lens": lens, "rhythm": rhythm, "beats": beats}


def emit_c(d: dict) -> str:
    def rows(vals, fmt, per):
        return ",\n".join("    " + ", ".join(fmt.format(v) for v in vals[i:i + per])
                          for i in range(0, len(vals), per))

    return (
        "/* GENERATED by firmware/tools/gen_stock_drums.py from the user's stock .mr.\n"
        " * Vendor data: do not commit. */\n"
        '#include "dsp/drums.h"\n\n'
        f"static const uint32_t events[{len(d['events'])}] = {{\n{rows(d['events'], '0x{:08x}', 6)}\n}};\n"
        f"static const uint16_t lens[{N_PATTERNS}] = {{\n{rows(d['lens'], '{}', 15)}\n}};\n"
        f"static const uint8_t rhythm[{N_RHYTHMS}] = {{\n{rows(d['rhythm'], '{}', 20)}\n}};\n"
        f"static const uint8_t beats[{N_PATTERNS}] = {{\n{rows(d['beats'], '{}', 30)}\n}};\n\n"
        "const drums_data_t stock_drums_data = {\n"
        f"    events, {len(d['events'])}, lens, {N_PATTERNS}, rhythm, {N_RHYTHMS}, beats,\n"
        "};\n"
    )


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    out = Path(argv[2])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(emit_c(extract(Path(argv[1]))))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
